version: '3'

volumes:
  ipa-data:

services:
  ipa:
    image: freeipa/freeipa-server:almalinux-9-4.11.0
    container_name: ipa
    environment:
        PASSWORD: Pa55w0rd
        DEBUG_TRACE: 1
        DEBUG_NO_EXIT: 1
    hostname: ipa.example.test
    # restart: always
    volumes:
     #- "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "ipa-data:/data:Z"
      # - IPA_SERVER_IP=172.16.30.18
    #command: ipa-server-install --realm='EXAMPLE.TEST' --no-ntp --netbios-name=EXAMPLE --setup-adtrust --setup-kra --enable-compat  --setup-dns --forwarder='1.1.1.1' --forward-policy=only --unattended
    # ports:
    #   - "53:53"
    #   - "80:80"
    #   - "443:443"
    #   - "389:389"
    #   - "636:636"
    #   - "88:88"
    #   - "464:464"
    #   - "88:88/udp"
    #   - "53:53/udp"
    #   - "464:464/udp"
    # networks:
    #   ipa_network:
    #     ipv4_address: 172.16.30.18
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=0
      
# networks:
#   ipa_network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.30.16/28
#           gateway: 172.16.30.17
#           aux_addresses:
#             dns: 172.16.30.18

# volumes:
#   ipa-data:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/tmp/ipadata'