version: '3'

volumes:
  postgres_data:
      driver: local
  freeipa_data:
      driver: local

services:
  freeipa:
      image: quay.io/freeipa/freeipa-server:almalinux-9-4.11.0
      volumes:
        - freeipa_data:/data
      environment:
        PASSWORD: Pa55w0rd
      hostname: localhost #ipa.sandbox.local
      #domainname: ipa.sandbox.local
      ports:
        - 53:53/udp
        - 53:53
        - 80:80
        - 443:443
        - 389:389
        - 636:636
        - 88:88
        - 464:464
        - 88:88/udp
        - 464:464/udp
      command:
        ipa-server-install
        --realm=EXAMPLE.TEST
        --no-ntp
  # postgres:
  #     image: postgres
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  #     environment:
  #       POSTGRES_DB: keycloak
  #       POSTGRES_USER: keycloak
  #       POSTGRES_PASSWORD: password
  # keycloak:
  #     image: quay.io/keycloak/keycloak:latest
  #     environment:
  #       #KC_HEALTH_ENABLED: true
  #       #KC_METRICS_ENABLED: true
  #       KC_HTTP_ENABLED: true
  #       KC_HOSTNAME_STRICT: false
  #       #KC_HOSTNAME: localhost
  #       KC_HOSTNAME_URL: http://localhost:8080
  #       KC_HOSTNAME_ADMIN_URL: http://localhost:8080

  #       #db
  #       KC_DB: postgres
  #       KC_DB_URL: jdbc:postgresql://postgres/keycloak
  #       KC_DB_USERNAME: keycloak
  #       KC_DB_PASSWORD: password

  #       #admin
  #       KEYCLOAK_ADMIN: admin
  #       KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd

  #       #logging
  #       KC_LOG_LEVEL: WARN,org.keycloak.saml.SAMLRequestParser:debug,sun.security.krb5:debug,sun.security.spnego:debug
  #       JAVA_OPTS_APPEND: -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true -Dkeycloak.profile.feature.account_api=enabled

  #       #features
  #       #KC_FEATURES: token-exchange
  #     command: 
  #       start-dev 
  #       --spi-events-listener-jboss-logging-success-level=WARN 
  #       --spi-events-listener-jboss-logging-error-level=WARN
  #       --log-level=WARN,org.keycloak.saml.SAMLRequestParser:debug,sun.security.krb5:debug,sun.security.spnego:debug
  #     ports:
  #       - 8080:8080
  #     depends_on:
  #       - postgres
