version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: bitnami/keycloak:latest
      environment:
        #KC_HEALTH_ENABLED: true
        #KC_METRICS_ENABLED: true
        KC_HTTP_ENABLED: true
        KEYCLOAK_HOSTNAME_STRICT: false
        #KC_HOSTNAME: localhost
        # keycloak should be in /etc/hosts
        KEYCLOAK_HOSTNAME: http://keycloak:8080
        KEYCLOAK_HOSTNAME_ADMIN: http://keycloak:8080

        #db
        KEYCLOAK_DATABASE_HOST: postgres
        KEYCLOAK_DATABASE_NAME: keycloak
        KEYCLOAK_DATABASE_USER: keycloak
        KEYCLOAK_DATABASE_PASSWORD: password

        #admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd

        #logging
        KEYCLOAK_LOG_LEVEL: WARN,org.keycloak.saml.SAMLRequestParser:debug,sun.security.krb5:debug,sun.security.spnego:debug
        KEYCLOAK_EXTRA_ARGS: -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true -Dkeycloak.profile.feature.account_api=enabled
        KEYCLOAK_EXTRA_ARGS_PREPENDED: --spi-events-listener-jboss-logging-success-level=WARN --spi-events-listener-jboss-logging-error-level=WARN

        #features
        #KC_FEATURES: token-exchange
      ports:
        - 8080:8080
      depends_on:
        - postgres  
  keycloak2:
      image: bitnami/keycloak:latest
      environment:
        #KC_HEALTH_ENABLED: true
        #KC_METRICS_ENABLED: true
        KC_HTTP_ENABLED: true
        KEYCLOAK_HOSTNAME_STRICT: false
        #KC_HOSTNAME: localhost
        KEYCLOAK_HOSTNAME: http://keycloak2:8082
        KEYCLOAK_HOSTNAME_ADMIN: http://keycloak2:8082

        #db
        KEYCLOAK_DATABASE_HOST: postgres
        KEYCLOAK_DATABASE_NAME: keycloak2
        KEYCLOAK_DATABASE_USER: keycloak
        KEYCLOAK_DATABASE_PASSWORD: password

        #admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd

        #logging
        KEYCLOAK_LOG_LEVEL: WARN,org.keycloak.saml.SAMLRequestParser:debug,sun.security.krb5:debug,sun.security.spnego:debug,org.keycloak.storage.ldap:trace
        KEYCLOAK_EXTRA_ARGS: -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true -Dkeycloak.profile.feature.account_api=enabled
        KEYCLOAK_EXTRA_ARGS_PREPENDED: --spi-events-listener-jboss-logging-success-level=WARN --spi-events-listener-jboss-logging-error-level=WARN
        #features
        #KC_FEATURES: token-exchange      
      ports:
        - 8082:8080
      depends_on:
        - postgres
